INSERT INTO series (series_title, series_name, person_name) VALUES ('Fast & Furious', 'fast_furious', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Thing', 'thing', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Dark Knight Returns', 'dark_knight_returns', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Train to Busan', 'train_to_busan', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Tarantino', 'tarantino', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Rush Hour', 'rush_hour', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('SAW', 'saw', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Cloverfield', 'cloverfield', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Death Note', 'death_note', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('The Matrix', 'the_matrix', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Hannibal', 'hannibal', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Star Wars', 'star_wars', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Insidious', 'insidious', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Gantz', 'gantz', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Shanghai Noon', 'shanghai_noon', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('American Pie', 'american_pie', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Final Destination', 'final_destination', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Terminator', 'terminator', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Austin Powers', 'austin_powers', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('John Wick', 'john_wick', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Riddick', 'riddick', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('The Dark Knight', 'the_dark_knight', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Drunken Master', 'drunken_master', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Ocean''s', 'oceans', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('The Raid', 'the_raid', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Die Hard', 'die_hard', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Jurassic Park', 'jurassic_park', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Bourne', 'bourne', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Alien', 'alien', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('James Bond', 'james_bond', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Mission Impossible', 'mission_impossible', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Scream', 'scream', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Blade Runner', 'blade_runner', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Underworld', 'underworld', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('V/H/S', 'vhs', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('A Quiet Place', 'a_quiet_place', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('The Hills Have Eyes', 'hills_have_eyes', 'DAN');
INSERT INTO series (series_title, series_name, person_name) VALUES ('Hostel', 'hostel', 'NICK');
INSERT INTO series (series_title, series_name, person_name) VALUES ('The Purge', 'purge', 'NICK');